### ISSUE TITLE
BadRequest : The document creation or update failed because of invalid reference

### ISSUE THREAD

**Issue by santoshdata** [SQLPlayer/azure.datafactory.tools#57] opened 2020-11-26 08:22 UTC
**Describe the bug**
Components are part of exclusion but still is being deployed and throwing an error . I have added multiple pipelines and its reference datasets as a part of exclusion. But observed in log that it is trying to deploy and update its datasets also. 

**To Reproduce**
IT is producible on large scale of ADF components on small chunk of components issue was not produciable. I have sent you log on your mail **kamil@sqlplayer.net**

**Screenshots**

**Version of PowerShell module of:**
 - azure.datafactory.tools [e.g.0.10.1]
<img width="696" alt="Error screenshot" src="https://user-images.githubusercontent.com/58113211/100325334-76653c00-2fee-11eb-8476-1478793ad135.PNG">

**Comment by NowinskiK** [comment] 2020-11-26 10:45
@santoshdata , isn't this a duplicate of #56 ?

**Comment by NowinskiK** [comment] 2020-11-27 00:54
hey @santoshdata.

The root cause of this error is related to dependencies and excluded object which needs to be deployed due to the reference from other object.
You are trying to deploy `sp_temp` which refers to `rdbn_hist_2`, but you excluded the object by this rule:
```
-dataset.rdbn_hist*
```
![image](https://user-images.githubusercontent.com/25029325/100399514-020cb600-304b-11eb-82c6-b25ebe317c8c.png)
I hope this explains everything in this case.

**Closed** 2020-11-27 00:56 UTC
