### ISSUE TITLE
Removing Datasets before related Data Flows error

### ISSUE THREAD

**Issue by soccerjoshj07** [SQLPlayer/azure.datafactory.tools#106] opened 2021-05-14 20:36 UTC
I recently renamed some datasets and data flows in my DataFactory instance and went to deploy them using this task, and I received a lot of errors:

```Removing object: [Dataset].[MyDataset]
##[debug]The document cannot be deleted since it is referenced by MyDataset.
Removing object: [Dataset].[MyDataset]
##[debug]The document cannot be deleted since it is referenced by MyDataset.
Removing object: [Dataset].[MyDataset]
##[debug]The document cannot be deleted since it is referenced by MyDataset.
Removing object: [Dataset].[MyDataset]
##[debug]The document cannot be deleted since it is referenced by MyDataset.
Removing object: [Dataset].[MyDataset]
##[debug]The document cannot be deleted since it is referenced by MyDataset.
Removing object: [Dataset].[MyDataset]
##[debug]The document cannot be deleted since it is referenced by MyDataset.
...
```

This occured for about 1000+ lines of the log before failing out with

```
##[debug]Leaving D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.6.846\PublishADF.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Remove-AdfObject : The script failed due to call depth overflow.
##[debug]At D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.6.846\ps_modules\azure.datafactory.tools\private\Remove-AdfObject.ps1:101 char:13
##[debug]+             Remove-AdfObject -adfSource $adfSource -obj $_ -adfInstan ...
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (0:Int32) [Remove-AdfObject], RuntimeException
##[debug]    + FullyQualifiedErrorId : CallDepthOverflow,Remove-AdfObject

...

##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: The script failed due to call depth overflow. ---> System.Management.Automation.ScriptCallDepthException: The script failed due to call depth overflow.
##[debug]   at System.Management.Automation.ExecutionContext.CheckStackDepth()
##[debug]   at System.Management.Automation.CommandProcessorBase.DoExecute()
##[debug]   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
##[debug]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
##[debug]   at Remove-AdfObject(Closure , FunctionContext )
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at Remove-AdfObject(Closure , FunctionContext )
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()

##[error]The script failed due to call depth overflow.

```

It seems like it ran in a loop for a long time before a depth overflow error occured, but the stem of the issue was that it couldn't remove the dataset because it is being used in a data flows of the same name.

The issue seems to be that it was deleting the dataset BEFORE the related data flow. It seems like a better process would. be to delete the data flow and THEN the dataset - at least in this scenario. The fix in my case was to open up the Data Factory I was deploying to and manually deleting all of the datasets / data flows and running another deployment, and then the deployment was successful. 

Is this something that can be switched around?

Thank you, let me know if you would like any more logs! Below are the inputs, from the log:

```
##[debug]INPUT_DATAFACTORYCODEPATH: 'D:\a\1\s'
##[debug]INPUT_DATAFACTORYNAME: 'QA-DATAFACTORY
##[debug]INPUT_RESOURCEGROUPNAME: 'QA-DATAFACTORY-RG'
##[debug]INPUT_LOCATION: 'North Central US'
##[debug]INPUT_STAGETYPE: 'FilePath'
##[debug]INPUT_STAGECODE (empty)
##[debug]INPUT_STAGECONFIGFILE: 'D:\a\1\s\deployment\config.csv'
##[debug]INPUT_DELETENOTINSOURCE: 'true'
##[debug] Converted to bool: True
##[debug]INPUT_STOPSTARTTRIGGERS: 'true'
##[debug] Converted to bool: True
##[debug]INPUT_CREATENEWINSTANCE: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_FILTERINGTYPE: 'None'
##[debug]INPUT_FILTERTEXTFILE: 'D:\a\1\s'
##[debug]INPUT_FILTERTEXT (empty)
##[debug]INPUT_PUBLISHMETHOD: 'AzResource'
##[debug]INPUT_DONOTSTOPSTARTEXCLUDEDTRIGGERS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_DONOTDELETEEXCLUDEDOBJECTS: 'true'
##[debug] Converted to bool: True
```

EDIT: Should this issue live in this repo instead? https://github.com/SQLPlayer/azure.datafactory.tools

**Comment by NowinskiK** [comment] 2021-05-18 07:50
Repo: no worries, I've just moved it here.
Thanks for raising this issue. To be honest, I need something which helps me reproduce the problem from scratch.
I will try to delete objects with the same name related to each other, but not sure if that's the problem.

**Comment by soccerjoshj07** [comment] 2021-05-18 17:23
What I would try is to re-create the issue would be to...

1. create a dataset and link it to a data flow and deploy it.
1. Then, rename the dataset and data flow and have the checkbox for to "delete objects not in source" checked. 
1. Then, run a deploy. The first part should lay down the newly named dataset and data flow, and then the next part of the deploy should be to delete the old dataset and data flow. 
1. It should try to delete the dataset before the data flow, which then causes the error.

**Comment by NowinskiK** [comment] 2021-06-10 20:39
I can't reproduce the error. See the branch and PS code attached:
https://github.com/SQLPlayer/azure.datafactory.tools/tree/issue-106/!issue-106
It works perfectly and removes all unnecessary objects.
![image](https://user-images.githubusercontent.com/25029325/121593781-2bfc5780-ca34-11eb-8264-6fef08bde169.png)

Feel free to attach code that reproducing the error and I will back to this issue.
In the meantime - I'm closing it.

**Closed by NowinskiK** 2021-06-10 20:39 UTC
Labels: triage
