### ISSUE TITLE
Bug deploying triggers that are started in target Data Factory

### ISSUE THREAD

**Issue by dsuarez993** [SQLPlayer/azure.datafactory.tools#71] opened 2020-12-23 00:28 UTC
**Describe the bug**
When deploying triggers that are started in the target Data Factory, the deployment fails, since they need to be stopped before deployment.

This behavior leads to enable $Option.StopStartTriggers=$True, but this affect all the triggers published in Data Factory.
I think this bug is related to #51 

**To Reproduce**
With triggers started in target Data Factory...
```
$Option.StopStartTriggers = $False
$Arguments = @{
    RootFolder = $this.AdfRootFolderPath;
    ResourceGroupName = $this.ResourceGroupName;
    DataFactoryName = $this.DataFactoryName;
    Location = $this.Location;
    Option = $Option;
    Stage = $this.ReplacePropertiesFilePath;
}
Publish-AdfV2FromJson @Arguments
```

**Expected behaviour**
Stop trigger if currently started, deploy trigger, and start again.

**Version of PowerShell module of:**
azure.datafactory.tools 0.17.0

**Comment by NowinskiK** [comment] 2020-12-23 09:45
@dsuarez993, this is not a bug, it was designed like that.
It is a user responsibility to take care of triggers and not deploy them when flag `StopStartTriggers` is set to `$false`.
However, as you noticed, the problem is wider and as such must be treated. 
Let me think about the concept, I will describe it and then crossed unit tests must be prepared along with the feature.

**Comment by dsuarez993** [comment] 2020-12-23 10:53
@NowinskiK yes, that was my impression when I started trying to fix the triggers issue.

Then, suddenly I started to think that maybe the `StopStartTriggers` was meant for another purpose, because it makes a lot of sense that sometimes you want to Stop all the triggers during deployment in order to avoid triggers to get triggered while other Adf objects related to it are being deployed, protecting the affected pipelines from failure. So I think this functionality in this way is very useful, but shouldn't be mandatory for deploying triggers.

As a bit of a context of how we are using this module: 
- We have several projects co-existing in the same Data Factory. We have a Git Repository for Data Factory, and we release a new Artifact with the Adf folder every time there is a change in master branch. 
- We have a Git Repository per Project with it's own versioned code (including Databricks Notebooks, SQL database solution..., and Data Factory deployment config files for this PowerShell Module, specifying what Adf Objects are related to the project).
- The CI/CD pipelines of each Git Repo project, (during Data Factory deployment task to TEST/PROD environments) takes the Adf Artifact, and perform the deployment using the ADF deployment config files, deploying only the Adf objects related to the project.

This is the reason why (in our case) not every trigger in the Adf folder source needs to be restarted in the target Data Facotry, and why sometimes they are not even deployed. 

Regarding the specific functionality/bug discussed in this issue, we don't need to StopStart all the other triggers not included in the project we are deploying, because they are not even related to the project, and they can be triggered and run pipelines without failing. 

So I think, the change in #72 fixes this behavior (maybe it should be implemented somewhere else?), allowing you to deploy triggers regardless their state in the target Data Factory. Moreover, you can still use `StopStartTriggers` functionallity if you need a full StopStart of all the triggers (this still should be fixed to start only the triggers present in the target Data Factory not the ones in source Adf folder).

Let me know if I can do anything to help :)

**Comment by NowinskiK** [comment] 2020-12-27 19:06
@dsuarez993 thanks for commenting this and sharding the lights onto a different way of managing and deploying ADF.
Although I'm not convenient keeping ADF code in that way - it may work for you and probably there are certain reasons behind that.  
However, the assumption of using this module is that you have all files existing in the source location.  
Aim of this module was to do the job and to not overcomplicate its usage.
An appropriate solution will be introduced in #51, but I hope it will cover your scenario as well.

**Closed by NowinskiK** 2020-12-27 19:06 UTC
Labels: duplicate

**Comment by dsuarez993** [comment] 2020-12-28 19:03
@NowinskiK we are not doing anything far from that assumption. We, indeed, use the full Source Adf folder, but it's just made available to other CI/CD pipelines through an Artifact in the Artifact Feed. We just cherry pick from there what to deploy for each project by applying the inclusion rules in the rules.txt file (the one I called ADF deployment config file before).

And I can tell you, this PowerShell module has been a turning point for us. I think the possibility of completely decoupling projects that share the same Data Factory is awesome. So if that was not the intention, it was an great side effect of it hahah. Thanks for all the great work!

P.S.: I've disabled `StopStartTriggers`, and added the logic in #72 as extra step to our own PowerShell code and now it works like a charm. So from our side we are ok, but I still think it would be a great addition to this module.

**Comment by NowinskiK** [comment] 2020-12-29 00:59
Really understand. But as long as you couldn't give me a clear picture of your case or build unit tests - I had to take into consideration all possible permutations. That's the picture:

![image](https://user-images.githubusercontent.com/25029325/103251551-05a89b00-4971-11eb-9ab2-f3a00be68918.png)


Take a look and let me know which cases are working not as you would expect.
Note: Flag `DoNotStopStartExcludedTriggers` (default: false) does not exist yet, but will be introduced in the new version and will change behaviour slightly. I'm wondering if "new behaviour" covers your needs.

**Comment by dsuarez993** [comment] 2020-12-29 15:30
@NowinskiK I have the feeling this is getting a bit overcomplicated.

In case you decide to go for the ´DoNotStopStartExcludedTriggers´ flag, the analysis is quite correct, but keeping in mind that the column is False for all rows, not all the permutations are covered "yet" and it would double the current list.

Although, I'm not agree with the resolution of some of the permutations: 
- **B08 and B09**: If you don't include those triggers in your deployment, why changing their state as in source? Just keep their current state. If you actually want to update the state of those triggers, just  include them to your deployment. (As an example of this, one of our data teams in their ADF have two Triggers that executes the same pipeline, one does it weekly, and the other daily. In Dev Environment they only enable the weekly, and in Test/Prod Environments they only enable the daily. If we apply this to them, in every deployment the state of those triggers will be overwritten with the Dev state, messing everything up.)
- **T01, T02, T09, and T10**: If triggers included but not present in Source, just raise a Warning, but don't change the state (they might be already published in that Data Factory and not in Source for a reason, like a hot fix added manually).
- **T03**: As in B08 and B09, if it's not included, keep the state even if not in Source. Again, it might be in that Data Factory and not in Source for a good reason.
- **T13**: This is a difficult one. I think that if a Trigger is included in a deployment but not in Source, it can only mean that somebody forgot to remove that line from the rules.txt file. I would just rise a Warning, and not an error since that can stop the whole deployment for a little mistake.
- **T15**: Also a bit difficult... I think in the safer option is to just raise a Warning and keep state, for the same reason as for T01, T02, T09, T10 and T13, that Trigger might be there enabled for a good reason. It is also true that if you are looking for "Deleting all not in source", it should be disabled, and then deleted.

What is the reasoning behind the initial design you mentioned before? Is it coming from the standard deploying approach where you have to stop all the triggers before publishing the Data Factory ARM template?
> @dsuarez993, this is not a bug, it was designed like that.
> It is a user responsibility to take care of triggers and not deploy them when flag `StopStartTriggers` is set to `$false`.
> However, as you noticed, the problem is wider and as such must be treated.
> Let me think about the concept, I will describe it and then crossed unit tests must be prepared along with the feature.

What is the issue of applying "before deploying a trigger, stop it if it's running, deploy it, and start it again if it was running before"? I think this could be the "by default" implementation, because otherwise you only get an error when deploying triggers that are already published and enabled. I don't see any potential damage of this.
 
In this case, I would keep `StopStartTriggers` to StopStart all triggers published in target Data Factory (in this case a rename of this flag by `StopStartAllTriggers` for transparency, keeping `StopStartTriggers` for retro-compatibility, and marked as "deprecated soon"). 

I think it will simplify really a lot the implementation, since you don't even have to add the new Flag `DoNotStopStartExcludedTriggers ` and put the effort of thinking about all the permutations, and implement the Unit Tests for them. 

Here I attach my version of all the permutations as I would like them to be:
![TriggerProposal](https://user-images.githubusercontent.com/31488342/103294344-02a1bf00-49f2-11eb-8598-0f9e2d04486f.png)

I hope it helps! Let me know what your thoughts are about this.

Thanks for all your time and effort! :)

**Comment by NowinskiK** [comment] 2021-01-03 20:23
Let me answer firstly on this:

> What is the reasoning behind the initial design you mentioned before? Is it coming from the standard deploying approach where you have to stop all the triggers before publishing the Data Factory ARM template?

Stopping all triggers is the safest and easiest way. Some other objects (like pipelines) are dependant on triggers. Deployment all objects in serial sequence might make the whole ADF inconsistent during the process, and I prefer to not invoke any trigger then.
Nevertheless, now you will be able to choose that behaviour more granularly using publish options.

**Comment by NowinskiK** [comment] 2021-01-03 20:37
@dsuarez993, thank you for your all comments, really appreciate it.
The following table presents planning logic when you use a new flag:
![image](https://user-images.githubusercontent.com/25029325/103488084-dcb95780-4e01-11eb-94db-be5c4d58d624.png)

Therefore, answering your comments:

Case | Comment
-- | --
T01 | This is because `StopStartTigeers`=true. If you want to avoid stopping the trigger - add it to 'excludes' list (looks like the object should be excluded   as does not exist in the source)
T02 | The same as above.
T03 | Yes, new concept will not disable the trigger (when `DoNotStopStartExcludedTriggers`=true)
T13 | Any mistakes must be fixed by developer as soon as possible and process should fail once the code or configuration is wrong. To avoid this case you may switch StopStartTriggers on.
T15 | Some rules I described below.


## StopStartTriggers
It allows you to decide. It stops ALL   existing and 'Started' (Enabled) triggers.
Generally you should use TRUE (default)   if you want to avoid troubles.
However, if you choose FALSE - you must   accept that process WILL NOT touch triggers. You can still do it for yourseft   in pre or post-deployment script.
 
## DoNotStopStartExcludedTriggers
In some scenarios, people still want to   let process to manage of triggers, but with some exceptions.
Usage of this flag make sense along with   StopStartTriggers only and some objects are excluded from deployment.
It guarantees that no (excluded) objects   will be even touched in target service during the deployment.
 
## Excluded (collection) 
should completely separate group of objects from   other group.
In that way you can keep all files in the   source but control behaviour with flags.
Exclusion can be defined in two ways:
1) Explicitly in 'Excludes' collection
2) Implicitly by not adding an item in   'Includes' collection
Important: Both collections can use   wildcards as the name of objects.
It simplify defining multiple objects by   one line, or defining objects which does not exist yet.
These collections are very useful while   you want to do a selective deployment.
 
## * DoNotDeleteExcludedObjects
Excluded object can be deleted only if   flag DoNotDeleteExcludedObjects = false
This situation could cause error when   trigger has not been deleted prior.
Otherwise, nothing will happen.
This option gives you a flexibility of deleting objects in the target, but still not touching objects from 'other'   group.
It comes from ticket #47 

I hope this is now a more clear and broader picture of the whole behaviour.

**Comment by dsuarez993** [comment] 2021-01-09 08:32
@NowinskiK thank you so much for the effort! I’ve just saw the new release.  Looking really good! I’ll test it later on :)

The explanation on the README it’s ver clear. But, do you think it would be good to complete the “matrix-of-behaviour-logic.png” with what happens if `DoNotStopStartTriggers` is False?

Thanks again! And I hope I won’t bother you anymore hahah

Cheers!

**Comment by NowinskiK** [comment] 2021-01-09 12:01
@dsuarez993 you are right, I totally forgot to put the second part of that table. I've just added it to [readme](../blob/master/README.md).  
No worries, I'm glad and very appreciative of all your comments. Every contribution only makes this module better.
And sorry that I couldn't approve your previous PRs. Now, you can see how sophisticated this problem was, how much efforts it required, why I wanted to come comprehensively to that, and why all unit tests are so crucial.

**Comment by NowinskiK** [comment] 2021-01-09 12:05
Please create a new issue in case of any new comments.
