### ISSUE TITLE
Values in destination ADF have change to strings this cause validation errors 

### ISSUE THREAD

**Issue by deanwest** [SQLPlayer/azure.datafactory.tools#66] opened 2020-12-18 15:41 UTC
**Describe the bug**
When I publish the values in the pipeline change from "retry": 0 to "retry": "0" this cause a validation error, I have also seen this happen on the "retryIntervalInSeconds" and "coreCount"

**To Reproduce**
Your script to reproduce the behaviour:
```
$SubscriptionName = ''
Set-AzContext -Subscription $SubscriptionName
$ResourceGroupName = ''
$DataFactoryName = ""
$Location = "UK South"
$RootFolder = "C:\Users\dean.west\Documents\Git_Repo\KPI_ADF\datafactory\KPI_ADF"

$adf = Import-AdfFromFolder -RootFolder "$RootFolder" -FactoryName $DataFactoryName

$list1 = $adf.GetObjectsByFolderName('Name')

$opt = New-AdfPublishOption
$opt.Includes += $list1
$opt.Includes.Add("linkedService.*", "")
$opt.Includes.Add("integrationruntime.*", "")
$opt.DeleteNotInSource = $false

Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location"  -Option $opt -Stage "UAT"
```

**Expected behaviour**
The JSON should be an int, not a string value 

**Screenshots**
Source:

 ],
                "policy": {
                    "timeout": "7.00:00:00",
                    "retry": 0,
                    "retryIntervalInSeconds": 30,
                    "secureOutput": false,
                    "secureInput": false
                },

"compute": {
                        "coreCount": 8,
                        "computeType": "General"
                    },

Destination:

  "policy": {
                    "timeout": "7.00:00:00",
                    "retry": "0",
                    "retryIntervalInSeconds": "30",
                    "secureOutput": "False",
                    "secureInput": "False"
                },

 "compute": {
                        "coreCount": "8",
                        "computeType": "General"
                    },

**Version of PowerShell module of:**
 - ### azure.datafactory.tools                                       Version 0.18.000 ###
 - Az.Datafactory Version 1.0.1

**Comment by NowinskiK** [comment] 2020-12-18 16:40
hi @deanwest. As you apply changes to the object using config file - could you attach these two files? (integrationruntime which contains `retry` field and UAT config file)

**Comment by deanwest** [comment] 2020-12-18 17:45
Hi @NowinskiK 

I have attached the file but I had to change some values. I have uploaded 3 files 

1. config file
2. Source github of a pipeline that has the"retry" and "retryIntervalInSeconds"
3. Destination code extracted from the UI of a pipeline that has the"retry" and "retryIntervalInSeconds" you can see the values have changed. 

I would like to also mention that this has happened to every pipeline and every object inside the pipeline. This was working and I have published to this ADF about 30 times with no issues. I had not updated or installed any new ps modules. I use vscode powershell integrated console 5.1 to publish to the new ADF.

[Logistics_Fact_Load_GIT_Source.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/5717177/Logistics_Fact_Load_GIT_Source.txt)
[Logistics_Fact_Load_ADF_Dest.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/5717196/Logistics_Fact_Load_ADF_Dest.txt)
 
[config-uat.xlsx](https://github.com/SQLPlayer/azure.datafactory.tools/files/5717149/config-uat.xlsx)

Thanks for looking into this appreciate it.

**Comment by deanwest** [comment] 2020-12-18 21:33
I don't know if this will help you but I trace the code back to see what the Definition of the object is when It gets published. I used the code below to find what I was looking for. 

```
$adf = Import-AdfFromFolder -FactoryName $DataFactoryName -RootFolder "$RootFolder"
$obj = $adf.AllObjects()[20]
$body = (Get-Content -Path $obj.FileName -Encoding "UTF8" | Out-String)
$json = $body | ConvertFrom-Json
$json.properties.activities.policy | get-member
```

The json passed into New-AzResource looks correct to me

```
Name                   MemberType   Definition
----                   ----------   ----------
Equals                 Method       bool Equals(System.Object obj)
GetHashCode            Method       int GetHashCode()
GetType                Method       type GetType()
ToString               Method       string ToString()
retry                  NoteProperty int retry=0
retryIntervalInSeconds NoteProperty int retryIntervalInSeconds=30
secureInput            NoteProperty bool secureInput=False
secureOutput           NoteProperty bool secureOutput=False
timeout                NoteProperty string timeout=7.00:00:00
```
I ran the command Publish-AdfV2FromJson in debug mode and found that the value looks like it changes when the API request is made. I don't know how to test this but I thought this might save you some time. 

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/<removed>/resourceGroups/<removed>/providers/Microsoft.DataFactory/factories/<removed>/pipelines/Logistics_Fact_Load?api-version=2018-06-01

Headers:
User-Agent              : PSVersion/v2020.6.0,AzurePowershell/v1.0.0
ParameterSetName        : BySubscriptionLevel
CommandName             : New-AzResource

Body:
{
  "name": "Logistics_Fact_Load",
  "properties": {
    "activities": [
      {
        "name": "GetFactCustomerMetadata",
        "type": "Lookup",
        "dependsOn": [],
        "policy": {
          "timeout": "7.00:00:00",
          "retry": "0",
          "retryIntervalInSeconds": "30",
          "secureOutput": "False",
          "secureInput": "False"
        },
```

**Comment by deanwest** [comment] 2020-12-18 22:43
**Workaround the issue:** 

Publish-AdfV2FromJson -method default is 'AzResource' by changing this to 'AzDataFactory' it resolves my issue. 

example is taken from the command

```
# Publish entire ADF via Az.DataFactory module instead of Az.Resources
Publish-AdfV2FromJson -RootFolder "$RootFolder" -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$DataFactoryName" -Location "$Location" -Method "AzDataFactory" 
```

**Comment by NowinskiK** [comment] 2020-12-19 00:41
@deanwest thanks for extra information. The files you sent me did not help too much. ;) Config file was not related to pipeline file.  
I investigate `Update-PropertiesFromFile` as I thought that the problem might be there. In the meantime you came with extra details, thanks.  
However, all ADF objects should be properly deployed by both methods: 'AzResource' as well as 'AzDataFactory', where 'AzResource', as you probably know, is more generic and uses in order to deployment for all objects in Azure.
**Question:** Do you have this issue only on your local machine? What if you use Azure DevOps and Hosted Agent?
I suspect that you might have some old PowerShell modules. Did you update all Az.* module?

**Comment by NowinskiK** [comment] 2020-12-23 09:54
@deanwest as no replies from you, I can't reproduce the error and no one else raised such issue - I'm gonna close this ticket.
But I'm keen to reopen it when you help me to reproduce the steps.

**Closed by NowinskiK** 2020-12-23 09:54 UTC
Labels: question

**Comment by deanwest** [comment] 2021-01-19 16:35
@NowinskiK I wanted to give you an update. 

I have moved from my local machine to Azure Devops to deploy the config. 
The issue is not present when I use Azure Devops when and using the UI. Must be an issue with my local environment. Thanks for all the help and a great product. 

Cheers
Dean

**Comment by NowinskiK** [comment] 2021-01-19 18:01
@deanwest glad to hear that. Thanks and enjoy!
