### ISSUE TITLE
Error with stopping triggers

### ISSUE THREAD

**Issue by norman-v** [SQLPlayer/azure.datafactory.tools#10] opened 2020-05-28 09:18 UTC
**Is your feature request related to a problem? Please describe.**
When it tries to stop triggers, it gives the following error message:
```
....
STEP: Stopping triggers...
Getting triggers...
triggerSortUtil : Cannot process argument transformation on parameter 'trigger'. Cannot convert the 
"Microsoft.Azure.Commands.DataFactoryV2.Models.PSTrigger" value of type 
"Microsoft.Azure.Commands.DataFactoryV2.Models.PSTrigger" to type 
"Microsoft.Azure.Commands.DataFactoryV2.Models.PSTrigger".

<my user directory here...>\azure.datafactory.tools\0.8.0\private\Get-SortedTriggers.ps1:11 char:58
+     $triggers | ForEach-Object{ triggerSortUtil -trigger $_ -triggerN ...
+                                                          ~~
    + CategoryInfo          : InvalidData: (:) [triggerSortUtil], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,triggerSortUtil
 
triggerSortUtil : Cannot process argument transformation on parameter 'trigger'. Cannot convert the 
"Microsoft.Azure.Commands.DataFactoryV2.Models.PSTrigger" value of type 
"Microsoft.Azure.Commands.DataFactoryV2.Models.PSTrigger" to type 
"Microsoft.Azure.Commands.DataFactoryV2.Models.PSTrigger".
```
**Describe the solution you'd like**
Seems like a code bug. Although I think it would be better if this flag is automatically determined if a trigger will be updated. For example, the above error came up even though I only had "pipeline.*" in my Includes so there was no need need to stop any triggers. If I deploy a trigger but this flag was turned off, an error appears saying I can't deploy a trigger that has not been disabled. So it seems like the value of this flag goes hand in hand with whether a trigger is deployed or not.

Other than this, this is an awesome and very useful module. Keep up the great work! Thanks!

**Comment by NowinskiK** [comment] 2020-05-28 15:44
Thanks @norman-v for raising this issue. I will take a look at this tonight.

**Comment by NowinskiK** [comment] 2020-05-29 01:52
I tested the module with a different kind of triggers and I can't reproduce the error.  
However, I have seen a similar error when I was testing and debugging the code in PowerShell session in VS Code during the development. Therefore, I guess you're playing with the code, probably importing internal (private) cmdlets as well. If so, please make sure to restart PowerShell session, import module in common method and run `Publish-AdfV2FromJson` function again.

**Comment by NowinskiK** [comment] 2020-06-01 12:14
@norman-v, I'm going to close this issue now, but let me know when you would be able to reproduce the issue with restarted PowerShell session and provide me these steps.

**Closed by NowinskiK** 2020-06-01 12:14 UTC
Labels: question
