### ISSUE TITLE
No restart all triggers

### ISSUE THREAD

**Issue by Cshion** [SQLPlayer/azure.datafactory.tools#51] opened 2020-10-29 21:57 UTC
**Describe the bug**
When StopStartTriggers option is activated it restarts all triggers in Datafactory instace disrupting some of them. How can I just restart triggers I want to update?

**To Reproduce**
$opt = New-AdfPublishOption 
$opt.StopStartTriggers = $true

**Expected behaviour**
Restart only triggers I specified in rules.txt file

**Version of PowerShell module of:**
 - azure.datafactory.tools 0.16
- Az.Datafactory 1.10.0

**Comment by artsheikoupply** [comment] 2020-12-02 10:55
@Cshion ,
As a workaround, you can desactivate all triggers in a src env before the deployment and use Stage csv / json config files to activate the triggers you need via "update" action.

Example 
deployment/config-prd.json

```
"myTriggerName": [
    {
      "name": "$.properties.runtimeState",
      "value": "Started",
      "action": "update"
    }
  ]
```

@NowinskiK,
I agree that the action type "restart" may be an enhancement. On the other hand, to avoid the new action-type that will be applicable only for a specific object (trigger), maybe we can have just an opt parameter "DesactivateAllTriggersOnTargetStage" ? That will allow to desactivate all target stage triggers and apply the solution described above to activate only specified ones by user.
An additional benefit is that we cannot always track what the team is doing in the DEV environment. Sometimes someone can create and activate a trigger for tests, and at the same time, it is necessary to deploy to a QA environment. The newly added trigger will be deployed and activated in QA, but we would like to avoid this. At the moment there is no other solution but to add new rules to Stage files (in this exemple, config-qa.json) with "runtimeState": "Stopped" for the triggers described.

**Comment by artsheiko** [comment] 2020-12-02 11:00
@Cshion ,
As a workaround, you can desactivate all triggers in a src env before the deployment and use Stage csv / json config files to activate the triggers you need via "update" action.

Example 
deployment/config-prd.json

```
"myTriggerName": [
    {
      "name": "$.properties.runtimeState",
      "value": "Started",
      "action": "update"
    }
  ]
```

@NowinskiK,
I agree that the action type "restart" may be an enhancement. On the other hand, to avoid the new action-type that will be applicable only for a specific object (trigger), maybe we can have just an opt parameter "DesactivateAllTriggersOnTargetStage" ? That will allow to desactivate all target stage triggers and apply the solution described above to activate only specified ones by user.

An additional benefit is that we cannot always track what the team is doing in the DEV environment. Sometimes someone can create and activate a trigger for tests, and at the same time, it is necessary to deploy to a QA environment. The newly added trigger will be deployed and activated in QA, but we would like to avoid this. At the moment there is no other solution but to add new rules to Stage files (in this exemple, config-qa.json) with "runtimeState": "Stopped" for the triggers described.

**Comment by NowinskiK** [comment] 2020-12-02 16:16
**Let me summarize how it works now (ver.0.18). If option `StopStartTriggers` is:**
- false - Stop & Start actions are skipped 
- true - Before deployment started, it stops all Active triggers
       - After deployment happened, it activates all triggers which have "Started" in JSON file  
No matter what, the deployment based on JSON files and (optionally) on config file.

> Restart only triggers I specified in rules.txt file  

@Cshion, what do you mean by _Restart_? Do you want to avoid for selected triggers by:
a) stopping (disabling) them?
b) activate (enabling) them?
Or, perhaps, you want to have all triggers disabled after the deployment?
What do you mean by "disrupting some of them"? 
c) Some triggers should not be even touched even when they are active (as you're not planning to deploy them by exclusion)
d) Some triggers are not active, but you don't want to change their status, no matter what is in JSON definition

@artsheiko, thanks for your comment and your perspective on this.
I agree that the scenario you've described here might be tricky right now.
To manage that, I'm considering provide one of these (or both) capabilities:
1) IgnoreActivatingTriggers - if true - no trigger will be activated, no matter what's defined in config.
2) wildcard for the name of objects in the config file - this enables you to define "Disabled" for all or selected triggers.

Guys, let me know what do you think. Personally, I'd prefer option 2 (wildcard) - it's already raised (#58) by my MVP fellow. 
@Cshion, would that option satisfy your needs?

**Comment by dsuarez993** [comment] 2020-12-14 12:43
Hi @NowinskiK! I jump into this discussion, since I'm experiencing some issues with this as well.

In my opinion, only those triggers marked for deployment should be restarted (disabled-> deployed -> enabled (only if enabled in the source)), instead of restarting absolutely all the triggers in your ADF, which could lead to some big issues.

I already had a case, where I wanted to publish only one trigger, but then the other 8 I had already published (some enabled and others disabled) were disabled, then for some reason the script failed, leaving all the triggers disabled. As a result, I had to fix all the trigger states manually.

**Comment by dsuarez993** [comment] 2020-12-21 18:21
@NowinskiK I think this functionality really needs to get fixed ASAP. I found another big issue related to this.

It seems that the script tries to start all the triggers that are in the Adf Source Folder, not the ones published in the target Data Factory. This behavior causes an error when having triggers not published yet to the target Data Factory. 

See the screenshot:
<img width="319" alt="ScreenshotAdf" src="https://user-images.githubusercontent.com/31488342/102808929-6b20e880-43c1-11eb-9128-c78712af6b50.png">

**Comment by NowinskiK** [comment] 2020-12-21 20:04
Thank you, @dsuarez993. This will be right the next thing I will be looking at.

**Comment by NowinskiK** [comment] 2020-12-28 14:50
@dsuarez993, I can confirm that the problem occurs in a specific scenario:
- StopStartTriggers = $true
- Trigger exists in the source folder (enabled)
- Trigger does not exist in target ADF service
- Trigger is in 'excludes' collection (publish options)

I prepared the unit test which covers that case and now I can fix it.

**Comment by NowinskiK** [comment] 2020-12-28 17:15
@dsuarez993 the bug you mentioned here has been released in ver. 0.20.
The original part of the issue will be in the next version.

**Closed** 2021-01-08 20:00 UTC
Labels: enhancement
